# Generated by Django 4.1.7 on 2023-03-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='sensor_name',
            new_name='sensor_id',
        ),
    ]
