# Generated by Django 4.1.7 on 2023-03-29 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_alter_measurement_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='sensor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor'),
        ),
    ]
