# Generated by Django 4.1.7 on 2023-03-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_alter_measurement_sensor_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-created']},
        ),
    ]
